TIR-master/config/routes.rb
Tir::Application.routes.draw do
  devise_for :users

  get "home/index"

  resources :registros

  resources :clientes
  
  resources :atendimentos

  resources :tiposervicos

  resources :tecnicos

  resources :tipo_servicos

  resources :empresas

  
  match '/:locale' => 'home#index'

  root :to => 'home#index'

end

TIR-master/app/models/ability.rb
class Ability

  include CanCan::Ability

  def initialize(user)
  
    # Define abilities for the passed in user here. For example:
    user ||= User.new # guest user (not logged in)
       
       alias_action :read, :create, :update, :destroy, :to => :crud
       
       if user.role == "administrador" || user.role == "administrator"
         can :manage, :all
       end    

       if user.role == "cliente" || user.role == "cliente"
         can :crud, [Registro]
         can :read, [Atendimento]
       end
       if user.role == "tecnico" || user.role == "tecnico"
         can :crud, [Atendimento]
         can :read, [Cliente]
         can :read, [Tecnico]

       end
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

TIR-master/app/models/atendimento.rb
class Atendimento < ActiveRecord::Base
  belongs_to :tecnico
  belongs_to :registro
  attr_accessible :dataAtualizacao, :horaAtualizacao, :horaFinalizacao, :resolucao, :status, :sumario, :tecnico_id, :registro_id
end

TIR-master/app/models/cliente.rb
class Cliente < ActiveRecord::Base
  belongs_to :empresa
  attr_accessible :localidade, :lotacao, :matricula, :nome, :sobrenome, :empresa_id
end

TIR-master/app/models/empresa.rb
class Empresa < ActiveRecord::Base
  attr_accessible :codigoempresa, :localidade, :nome, :razaosocial
end

TIR-master/app/models/registro.rb
class Registro < ActiveRecord::Base
  belongs_to :tiposervico
  belongs_to :cliente
  attr_accessible :codregistro, :complemento, :data, :descricao, :hora, :tiposervico_id, :cliente_id
end

TIR-master/app/models/tecnico.rb
class Tecnico < ActiveRecord::Base
  belongs_to :tiposervico
  attr_accessible :especializacao, :matricula, :nome, :ocupacao, :tiposervico_id
end

TIR-master/app/models/tiposervico.rb
class Tiposervico < ActiveRecord::Base
  attr_accessible :descricao, :titulo
end

TIR-master/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :role
  # attr_accessible :title, :body
  validates_presence_of :email
  
   ROLES = %w[administrador cliente tecnico]
    
    def role_symbols
        [role.to_sym]
    end
    
    def role?(role)
        role.include?(role.to_s)
    end
  
end

TIR-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :authenticate_user!
  skip_authorization_check :unless => :devise_controller?
  
  before_filter :set_locale
  
  def set_locale
		I18n.locale = params[:locale] || I18n.default_locale
  end
  
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end
  protect_from_forgery
end

TIR-master/app/controllers/clientes_controller.rb
class ClientesController < InheritedResources::Base
  load_and_authorize_resource
end

TIR-master/app/controllers/empresas_controller.rb
class EmpresasController < InheritedResources::Base
  load_and_authorize_resource
end

TIR-master/app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		flash[:notice] = t(:presentation)
	end

end

TIR-master/app/controllers/registros_controller.rb
class RegistrosController < InheritedResources::Base
  load_and_authorize_resource
end

TIR-master/app/controllers/tecnicos_controller.rb
class TecnicosController < InheritedResources::Base
  load_and_authorize_resource
end

TIR-master/app/helpers/application_helper.rb
module ApplicationHelper

end

TIR-master/app/helpers/atendimentos_helper.rb
module AtendimentosHelper
end

TIR-master/app/helpers/clientes_helper.rb
module ClientesHelper
end

TIR-master/app/helpers/empresas_helper.rb
module EmpresasHelper
end

TIR-master/app/helpers/home_helper.rb
module HomeHelper
end

TIR-master/app/helpers/registros_helper.rb
module RegistrosHelper
end

TIR-master/app/helpers/tecnicos_helper.rb
module TecnicosHelper
end

TIR-master/app/helpers/tipo_servicos_helper.rb
module TipoServicosHelper
end

TIR-master/app/helpers/tiposervicos_helper.rb
module TiposervicosHelper
end

TIR-master/app/views/clientes/_form.html.erb
<%= form_for @cliente, :html => { :multipart => true } do |f| %>

    <p><%= f.label :matricula %><br />
    <%= f.text_field :matricula %></p>

    <p><%= f.label :nome %><br />
    <%= f.text_field :nome %></p>

    <p><%= f.label :sobrenome %><br />
    <%= f.text_field :sobrenome %></p>
    
    <p><%= f.label :lotacao %><br />
    <%= f.text_field :lotacao %></p>

    <p><%= f.label :localidade %><br />
    <%= f.text_field :localidade %></p>

    <p><%= f.label :empresa_id %><br />
    <%= f.collection_select :empresa_id, Empresa.all, :id, :nome %></br>           	        
    
    <%= f.submit %>

<% end %>

TIR-master/app/views/clientes/_form.html.haml
= semantic_form_for [@cliente] do |form|
  
  = form.input :matricula, :label => 'Matricula'
  = form.input :nome, :label => 'Nome' 
  = form.input :sobrenome, :label => 'Sobrenome' 
  = form.input :lotacao, :label => 'Lotacao' 
  = form.input :localidade, :label => 'Localidade'
  = form.input :empresa, :member_label => :nome, :label => 'empresa' 
  = form.submit 'Salvar'

TIR-master/app/views/clientes/edit.html.erb
<h1>Editing cliente</h1>

<%= render 'form' %>

<%= link_to 'Show', @cliente %> |
<%= link_to 'Back', clientes_path %>

TIR-master/app/views/clientes/index.html.erb
<h1>Lista de clientes</h1>

<table>
  <tr>
    <th>Matricula</th>
    <th>Nome</th>
    <th>Sobrenome</th>
    <th>Lotação</th>
    <th>Localidade</th>
    <th>Empresa</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clientes.each do |cliente| %>
  <tr>
    <td><%= cliente.matricula %></td>
    <td><%= cliente.nome %></td>
    <td><%= cliente.sobrenome %></td>
    <td><%= cliente.lotacao %></td>
    <td><%= cliente.localidade %></td>
    <td><%= cliente.empresa.nome %></td>
    <td><%= link_to 'Exibir', cliente %></td>
    <td><%= link_to 'Editar', edit_cliente_path(cliente) %></td>
    <td><%= link_to 'Excluir', cliente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Cadastrar Cliente', new_cliente_path %>

TIR-master/app/views/clientes/new.html.erb
<h1>Cadastrar cliente</h1>

<%= render 'form' %>

<%= link_to 'Voltar', clientes_path %>

TIR-master/app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Matricula:</b>
  <%= @cliente.matricula %>
</p>

<p>
  <b>Nome:</b>
  <%= @cliente.nome %>
</p>

<p>
  <b>Sobrenome:</b>
  <%= @cliente.sobrenome %>
</p>

<p>
  <b>Lotacao:</b>
  <%= @cliente.lotacao %>
</p>

<p>
  <b>Localidade:</b>
  <%= @cliente.localidade %>
</p>

<p>
  <b>Empresa:</b>
  <%= @cliente.empresa.nome %>
</p>


<%= link_to 'Edit', edit_cliente_path(@cliente) %> |
<%= link_to 'Back', clientes_path %>

TIR-master/app/views/empresas/_form.html.erb
<%= form_for @empresa, :html => { :multipart => true } do |f| %>

    <p><%= f.label :razaosocial %><br />
    <%= f.text_field :razaosocial %></p>

    <p><%= f.label :nome %><br />
    <%= f.text_field :nome %></p>

    <p><%= f.label :localidade %><br />
    <%= f.text_field :localidade %></p>
    
    <%= f.submit %>

<% end %>

TIR-master/app/views/empresas/_form.html.haml
= semantic_form_for [@empresa] do |form|

  = form.input :razaosocial, :label => 'Razaosocial'
  = form.input :nome, :label => 'Nome'
  = form.input :localidade, :label => 'Localidade'
  = form.submit 'Salvar'

TIR-master/app/views/empresas/edit.html.erb
<h1>Editing empresa</h1>

<%= render 'form' %>

<%= link_to 'Show', @empresa %> |
<%= link_to 'Back', empresas_path %>

TIR-master/app/views/empresas/index.html.erb
<h1>Empresas Cadastradas</h1>

<table>
  <tr>
    <!--<th>Codigo da empresa</th>-->
    <th>Razão social</th>
    <th>Nome</th>
    <th>Localidade</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @empresas.each do |empresa| %>
  <tr>
    <!--<td><%= empresa.codigoempresa %></td>-->
    <td><%= empresa.razaosocial %></td>
    <td><%= empresa.nome %></td>
    <td><%= empresa.localidade %></td>
    <td><%= link_to 'Exibir', empresa %></td>
    <td><%= link_to 'Editar', edit_empresa_path(empresa) %></td>
    <td><%= link_to 'Excluir', empresa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Cadastrar Empresa', new_empresa_path %>

TIR-master/app/views/empresas/new.html.erb
<h1>Cadastrar empresa</h1>

<%= render 'form' %>

<%= link_to 'Voltar', empresas_path %>

TIR-master/app/views/empresas/show.html.erb
<p id="notice"><%= notice %></p>

<!--<p>
  <b>Codigoempresa:</b>
  <%= @empresa.codigoempresa %>
</p>-->

<p>
  <b>Razaosocial:</b>
  <%= @empresa.razaosocial %>
</p>

<p>
  <b>Nome:</b>
  <%= @empresa.nome %>
</p>

<p>
  <b>Localidade:</b>
  <%= @empresa.localidade %>
</p>


<%= link_to 'Edit', edit_empresa_path(@empresa) %> |
<%= link_to 'Back', empresas_path %>

TIR-master/app/views/registros/_form.html.erb
<%= form_for @registro, :html => { :multipart => true } do |f| %>

    <p><%= f.label :descricao %><br />
    <%= f.text_field :descricao %></p>

    <p><%= f.label :complemento %><br />
    <%= f.text_field :complemento %></p>

    <p><%= f.label :data %><br />
    <%= f.text_field :data %></p>
    
    <p><%= f.label :hora %><br />
    <%= f.text_field :hora %></p>

    <p><%= f.label :tipo %><br />
    <%= f.collection_select :tiposervico_id, Tiposervico.all, :id, :titulo %></br> 
    
    <p><%= f.label :nome %><br />
    <%= f.collection_select :cliente_id, Cliente.all, :id, :nome %></br>

    <%= f.submit%>

<% end %>

TIR-master/app/views/registros/_form.html.haml
= semantic_form_for [@registro] do |form|
  
  = form.input :descricao, :label => 'Descricao' 
  = form.input :complemento, :label => 'Complemento' 
  = form.input :data, :as => :string, :label => 'Data'
  = form.input :hora, :label => 'Hora'
  = form.input :tiposervico, :member_label => :titulo, :label => 'Tiposervico'
  = form.input :cliente, :member_label => :nome, :label => 'Cliente'
  = form.submit 'Salvar'

TIR-master/app/views/registros/edit.html.erb
<h1>Editing registro</h1>

<%= render 'form' %>

<%= link_to 'Show', @registro %> |
<%= link_to 'Back', registros_path %>

TIR-master/app/views/registros/index.html.erb
<h1>Lista de registros</h1>

<table>
  <tr>
 	<!--<th>Codigo do registro</th> -->
    <th>Descrição</th>
    <th>Complemento</th>
    <th>Data</th>
    <th>Hora</th>
    <th>Tipo</th>
    <th>Cliente</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @registros.each do |registro| %>
  <tr>
    <!--<td><%= registro.codregistro %></td>-->
    <td><%= registro.descricao %></td>
    <td><%= registro.complemento %></td>
    <td><%= registro.data %></td>
    <td><%= registro.hora %></td>
    <td><%= registro.tiposervico.titulo %></td>
    <td><%= registro.cliente.nome %></td>
    <td><%= link_to 'Exibir', registro %></td>
    <td><%= link_to 'Editar', edit_registro_path(registro) %></td>
    <td><%= link_to 'Excluir', registro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Novo Registro', new_registro_path %>

TIR-master/app/views/registros/new.html.erb
<h1>Criar registro</h1>

<%= render 'form' %>

<%= link_to 'Voltar', registros_path %>

TIR-master/app/views/registros/show.html.erb
<p id="notice"><%= notice %></p>

<!--<p>
  <b>Código do registro:</b>
  <%= @registro.codregistro %>
</p>-->

<p>
  <b>Descricao:</b>
  <%= @registro.descricao %>
</p>

<p>
  <b>Complemento:</b>
  <%= @registro.complemento %>
</p>

<p>
  <b>Data:</b>
  <%= @registro.data %>
</p>

<p>
  <b>Hora:</b>
  <%= @registro.hora %>
</p>

<p>
  <b>Tiposervico:</b>
  <%= @registro.tiposervico.titulo %>
</p>

<p>
  <b>Cliente:</b>
  <%= @registro.cliente.nome %>
</p>


<%= link_to 'Edit', edit_registro_path(@registro) %> |
<%= link_to 'Back', registros_path %>

TIR-master/app/views/tecnicos/_form.html.erb
<%= form_for @tecnico, :html => { :multipart => true } do |f| %>

    <p><%= f.label :matricula %><br />
    <%= f.text_field :matricula %></p>

    <p><%= f.label :nome %><br />
    <%= f.text_field :nome %></p>

    <p><%= f.label :ocupacao %><br />
    <%= f.text_field :ocupacao %></p>
    
    <p><%= f.label :especializacao %><br />
    <%= f.text_field :especializacao %></p>

    <p><%= f.label :titulo %><br />
    <%= f.collection_select :tiposervico_id, Tiposervico.all, :id, :titulo %></br>
    
    <%= f.submit %>

<% end %>

TIR-master/app/views/tecnicos/_form.html.haml
= semantic_form_for [@tecnico] do |form|
  
  = form.input :matricula, :label => 'Matricula'
  = form.input :nome, :label => 'Nome' 
  = form.input :ocupacao, :label => 'Ocupacao' 
  = form.input :especializacao, :label => 'Especializacao'
  = form.input :tiposervico, :member_label => :titulo, :label => 'tiposervico' 
  = form.submit 'Salvar'

TIR-master/app/views/tecnicos/edit.html.erb
<h1>Editing tecnico</h1>

<%= render 'form' %>

<%= link_to 'Show', @tecnico %> |
<%= link_to 'Back', tecnicos_path %>

TIR-master/app/views/tecnicos/index.html.erb
<h1>Lista de Tecnicos</h1>

<table>
  <tr>
    <th>Matricula</th>
    <th>Nome</th>
    <th>Ocupacao</th>
    <th>Especializacao</th>
    <th>Tipo de serviço</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tecnicos.each do |tecnico| %>
  <tr>
    <td><%= tecnico.matricula %></td>
    <td><%= tecnico.nome %></td>
    <td><%= tecnico.ocupacao %></td>
    <td><%= tecnico.especializacao %></td>
    <td><%= tecnico.tiposervico.titulo %></td>
    <td><%= link_to 'Exibir', tecnico %></td>
    <td><%= link_to 'Editar', edit_tecnico_path(tecnico) %></td>
    <td><%= link_to 'Excluir', tecnico, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Cadastrar Tecnico', new_tecnico_path %>

TIR-master/app/views/tecnicos/new.html.erb
<h1>Cadastrar Técnico</h1>

<%= render 'form' %>

<%= link_to 'Voltar', tecnicos_path %>

TIR-master/app/views/tecnicos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Matricula:</b>
  <%= @tecnico.matricula %>
</p>

<p>
  <b>Nome:</b>
  <%= @tecnico.nome %>
</p>

<p>
  <b>Ocupacao:</b>
  <%= @tecnico.ocupacao %>
</p>

<p>
  <b>Especializacao:</b>
  <%= @tecnico.especializacao %>
</p>

<p>
  <b>Tiposervico:</b>
  <%= @tecnico.tiposervico.titulo %>
</p>


<%= link_to 'Edit', edit_tecnico_path(@tecnico) %> |
<%= link_to 'Back', tecnicos_path %>
 