TIR-master/config/routes.rb
Tir::Application.routes.draw do
  devise_for :users

  get "home/index"

  resources :registros

  resources :clientes
  
  resources :atendimentos

  resources :tiposervicos

  resources :tecnicos

  resources :tipo_servicos

  resources :empresas

  
  match '/:locale' => 'home#index'

  root :to => 'home#index'

end

TIR-master/app/models/ability.rb
class Ability

  include CanCan::Ability

  def initialize(user)
  
    # Define abilities for the passed in user here. For example:
    user ||= User.new # guest user (not logged in)
       
       alias_action :read, :create, :update, :destroy, :to => :crud
       
       if user.role == "administrador" || user.role == "administrator"
         can :manage, :all
       end    

       if user.role == "cliente" || user.role == "cliente"
         can :crud, [Registro]
         can :read, [Atendimento]
       end
       if user.role == "tecnico" || user.role == "tecnico"
         can :crud, [Atendimento]
         can :read, [Cliente]
         can :read, [Tecnico]

       end
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

TIR-master/app/models/atendimento.rb
class Atendimento < ActiveRecord::Base
  belongs_to :tecnico
  belongs_to :registro
  attr_accessible :dataAtualizacao, :horaAtualizacao, :horaFinalizacao, :resolucao, :status, :sumario, :tecnico_id, :registro_id
end

TIR-master/app/models/cliente.rb
class Cliente < ActiveRecord::Base
  belongs_to :empresa
  attr_accessible :localidade, :lotacao, :matricula, :nome, :sobrenome, :empresa_id
end

TIR-master/app/models/empresa.rb
class Empresa < ActiveRecord::Base
  attr_accessible :codigoempresa, :localidade, :nome, :razaosocial
end

TIR-master/app/models/registro.rb
class Registro < ActiveRecord::Base
  belongs_to :tiposervico
  belongs_to :cliente
  attr_accessible :codregistro, :complemento, :data, :descricao, :hora, :tiposervico_id, :cliente_id
end

TIR-master/app/models/tecnico.rb
class Tecnico < ActiveRecord::Base
  belongs_to :tiposervico
  attr_accessible :especializacao, :matricula, :nome, :ocupacao, :tiposervico_id
end

TIR-master/app/models/tiposervico.rb
class Tiposervico < ActiveRecord::Base
  attr_accessible :descricao, :titulo
end

TIR-master/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :role
  # attr_accessible :title, :body
  validates_presence_of :email
  
   ROLES = %w[administrador cliente tecnico]
    
    def role_symbols
        [role.to_sym]
    end
    
    def role?(role)
        role.include?(role.to_s)
    end
  
end

TIR-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :authenticate_user!
  skip_authorization_check :unless => :devise_controller?
  
  before_filter :set_locale
  
  def set_locale
		I18n.locale = params[:locale] || I18n.default_locale
  end
  
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end
  protect_from_forgery
end

TIR-master/app/controllers/clientes_controller.rb
class ClientesController < InheritedResources::Base
  load_and_authorize_resource
end

TIR-master/app/controllers/empresas_controller.rb
class EmpresasController < InheritedResources::Base
  load_and_authorize_resource
end

TIR-master/app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		flash[:notice] = t(:presentation)
	end

end

TIR-master/app/controllers/registros_controller.rb
class RegistrosController < InheritedResources::Base
  load_and_authorize_resource
end

TIR-master/app/controllers/tecnicos_controller.rb
class TecnicosController < InheritedResources::Base
  load_and_authorize_resource
end

TIR-master/app/controllers/tipo_servicos_controller.rb
class TipoServicosController < InheritedResources::Base
  load_and_authorize_resource
end

TIR-master/app/controllers/tiposervicos_controller.rb
class TiposervicosController < InheritedResources::Base
  load_and_authorize_resource
end

TIR-master/app/helpers/application_helper.rb
module ApplicationHelper

end

TIR-master/app/helpers/atendimentos_helper.rb
module AtendimentosHelper
end

TIR-master/app/helpers/clientes_helper.rb
module ClientesHelper
end

TIR-master/app/helpers/empresas_helper.rb
module EmpresasHelper
end

TIR-master/app/helpers/home_helper.rb
module HomeHelper
end

TIR-master/app/helpers/registros_helper.rb
module RegistrosHelper
end

TIR-master/app/helpers/tecnicos_helper.rb
module TecnicosHelper
end

TIR-master/app/helpers/tipo_servicos_helper.rb
module TipoServicosHelper
end

TIR-master/app/helpers/tiposervicos_helper.rb
module TiposervicosHelper
end

TIR-master/app/views/tiposervicos/_form.html.erb
<%= form_for @tiposervico, :html => { :multipart => true } do |f| %>

    <p><%= f.label :titulo %><br />
    <%= f.text_field :titulo %></p>

    <p><%= f.label :descricao %><br />
    <%= f.text_field :descricao %></p>

    <%= f.submit %>

<% end %>

TIR-master/app/views/tiposervicos/_form.html.haml
= semantic_form_for [@tiposervico] do |form|
  = form.input :titulo, :label => 'Titulo'
  = form.input :descricao, :label => 'Descricao'
  = form.submit 'Salvar'

TIR-master/app/views/tiposervicos/edit.html.erb
<h1>Editing tiposervico</h1>

<%= render 'form' %>

<%= link_to 'Show', @tiposervico %> |
<%= link_to 'Back', tiposervicos_path %>

TIR-master/app/views/tiposervicos/index.html.erb
<h1>Lista de tipos de serviço</h1>

<table>
  <tr>
    <th>Titulo</th>
    <th>Descrição</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tiposervicos.each do |tiposervico| %>
  <tr>
    <td><%= tiposervico.titulo %></td>
    <td><%= tiposervico.descricao %></td>
    <td><%= link_to 'Exibir', tiposervico %></td>
    <td><%= link_to 'Editar', edit_tiposervico_path(tiposervico) %></td>
    <td><%= link_to 'Excluir', tiposervico, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Cadastrar tipo de serviço', new_tiposervico_path %>

TIR-master/app/views/tiposervicos/new.html.erb
<h1>Novo Tipo de Serviço</h1>

<%= render 'form' %>

<%= link_to 'Voltar', tiposervicos_path %>

TIR-master/app/views/tiposervicos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Titulo:</b>
  <%= @tiposervico.titulo %>
</p>

<p>
  <b>Descricao:</b>
  <%= @tiposervico.descricao %>
</p>


<%= link_to 'Edit', edit_tiposervico_path(@tiposervico) %> |
<%= link_to 'Back', tiposervicos_path %>