TIR-master/config/routes.rb
Tir::Application.routes.draw do
  devise_for :users

  get "home/index"

  resources :registros

  resources :clientes
  
  resources :atendimentos

  resources :tiposervicos

  resources :tecnicos

  resources :tipo_servicos

  resources :empresas

  
  match '/:locale' => 'home#index'

  root :to => 'home#index'

end

TIR-master/app/models/ability.rb
class Ability

  include CanCan::Ability

  def initialize(user)
  
    # Define abilities for the passed in user here. For example:
    user ||= User.new # guest user (not logged in)
       
       alias_action :read, :create, :update, :destroy, :to => :crud
       
       if user.role == "administrador" || user.role == "administrator"
         can :manage, :all
       end    

       if user.role == "cliente" || user.role == "cliente"
         can :crud, [Registro]
         can :read, [Atendimento]
       end
       if user.role == "tecnico" || user.role == "tecnico"
         can :crud, [Atendimento]
         can :read, [Cliente]
         can :read, [Tecnico]

       end
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

TIR-master/app/models/atendimento.rb
class Atendimento < ActiveRecord::Base
  belongs_to :tecnico
  belongs_to :registro
  attr_accessible :dataAtualizacao, :horaAtualizacao, :horaFinalizacao, :resolucao, :status, :sumario, :tecnico_id, :registro_id
end

TIR-master/app/models/cliente.rb
class Cliente < ActiveRecord::Base
  belongs_to :empresa
  attr_accessible :localidade, :lotacao, :matricula, :nome, :sobrenome, :empresa_id
end

TIR-master/app/models/empresa.rb
class Empresa < ActiveRecord::Base
  attr_accessible :codigoempresa, :localidade, :nome, :razaosocial
end

TIR-master/app/models/registro.rb
class Registro < ActiveRecord::Base
  belongs_to :tiposervico
  belongs_to :cliente
  attr_accessible :codregistro, :complemento, :data, :descricao, :hora, :tiposervico_id, :cliente_id
end

TIR-master/app/models/tecnico.rb
class Tecnico < ActiveRecord::Base
  belongs_to :tiposervico
  attr_accessible :especializacao, :matricula, :nome, :ocupacao, :tiposervico_id
end

TIR-master/app/models/tiposervico.rb
class Tiposervico < ActiveRecord::Base
  attr_accessible :descricao, :titulo
end

TIR-master/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :role
  # attr_accessible :title, :body
  validates_presence_of :email
  
   ROLES = %w[administrador cliente tecnico]
    
    def role_symbols
        [role.to_sym]
    end
    
    def role?(role)
        role.include?(role.to_s)
    end
  
end

TIR-master/app/controllers/clientes_controller.rb
class ClientesController < InheritedResources::Base
  load_and_authorize_resource
end

TIR-master/app/controllers/empresas_controller.rb
class EmpresasController < InheritedResources::Base
  load_and_authorize_resource
end

TIR-master/app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		flash[:notice] = t(:presentation)
	end

end

TIR-master/app/helpers/application_helper.rb
module ApplicationHelper

end

TIR-master/app/helpers/atendimentos_helper.rb
module AtendimentosHelper
end

TIR-master/app/helpers/clientes_helper.rb
module ClientesHelper
end

TIR-master/app/helpers/empresas_helper.rb
module EmpresasHelper
end

TIR-master/app/helpers/home_helper.rb
module HomeHelper
end

TIR-master/app/helpers/registros_helper.rb
module RegistrosHelper
end

TIR-master/app/helpers/tecnicos_helper.rb
module TecnicosHelper
end

TIR-master/app/helpers/tipo_servicos_helper.rb
module TipoServicosHelper
end

TIR-master/app/helpers/tiposervicos_helper.rb
module TiposervicosHelper
end

TIR-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--
Design by Free CSS Templates
http://www.freecsstemplates.org
Released for free under a Creative Commons Attribution 2.5 License
Name : Regeneracy
Description: A two-column, fixed-width design with dark color scheme.
Version : 1.0
Released : 20100529
-->
<html xmlns="http://ww w.w3.org/1999/xhtml">
<head>
<meta name="keywords" content="" />
<meta name="description" content="" />
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Request TI</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :application %>
  <%= csrf_meta_tag %>
</head>
<body>
<div id='wrapper'>
<div id='header-wrapper'>
<div id='header'>
<div id='logo'>
<h1><a href='/'>Request TI</a></h1>
                                
</div>
<div id = 'menu'>
<ul>

 <!--<li><%= link_to 'Empresa',empresas_path %></li>-->
 <li><%= link_to I18n.t('empresa'), empresas_path %></li>
 <li><%= link_to I18n.t('cliente'), clientes_path %></li>
 <li><%= link_to I18n.t('registro'), registros_path %></li>
 <li><%= link_to I18n.t('tiposDeServico'), tiposervicos_path %></li>
 <li><%= link_to I18n.t('tecnico'), tecnicos_path %></li>
 <li><%= link_to I18n.t('atendimento'), atendimentos_path %></li>

</ul>
</div>
                </div>
           </div>
<div id='page'>

<div id='page-bgtop'>
<div id='page-bgbtm'>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>
<div style='clear: both;'> </div>
</div>
</div>

</div>
   
</div>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      
      <p class="navbar-text pull-right">
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to "Edit profile", edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
      </p>
    </div>
  </div>
</div>

</body>
</html>