TIR-master/config/routes.rb
Tir::Application.routes.draw do
  devise_for :users

  get "home/index"

  resources :registros

  resources :clientes
  
  resources :atendimentos

  resources :tiposervicos

  resources :tecnicos

  resources :tipo_servicos

  resources :empresas

  
  match '/:locale' => 'home#index'

  root :to => 'home#index'

end

TIR-master/app/models/ability.rb
class Ability

  include CanCan::Ability

  def initialize(user)
  
    # Define abilities for the passed in user here. For example:
    user ||= User.new # guest user (not logged in)
       
       alias_action :read, :create, :update, :destroy, :to => :crud
       
       if user.role == "administrador" || user.role == "administrator"
         can :manage, :all
       end    

       if user.role == "cliente" || user.role == "cliente"
         can :crud, [Registro]
         can :read, [Atendimento]
       end
       if user.role == "tecnico" || user.role == "tecnico"
         can :crud, [Atendimento]
         can :read, [Cliente]
         can :read, [Tecnico]

       end
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

TIR-master/app/models/atendimento.rb
class Atendimento < ActiveRecord::Base
  belongs_to :tecnico
  belongs_to :registro
  attr_accessible :dataAtualizacao, :horaAtualizacao, :horaFinalizacao, :resolucao, :status, :sumario, :tecnico_id, :registro_id
end

TIR-master/app/models/cliente.rb
class Cliente < ActiveRecord::Base
  belongs_to :empresa
  attr_accessible :localidade, :lotacao, :matricula, :nome, :sobrenome, :empresa_id
end

TIR-master/app/models/empresa.rb
class Empresa < ActiveRecord::Base
  attr_accessible :codigoempresa, :localidade, :nome, :razaosocial
end

TIR-master/app/models/registro.rb
class Registro < ActiveRecord::Base
  belongs_to :tiposervico
  belongs_to :cliente
  attr_accessible :codregistro, :complemento, :data, :descricao, :hora, :tiposervico_id, :cliente_id
end

TIR-master/app/models/tecnico.rb
class Tecnico < ActiveRecord::Base
  belongs_to :tiposervico
  attr_accessible :especializacao, :matricula, :nome, :ocupacao, :tiposervico_id
end

TIR-master/app/models/tiposervico.rb
class Tiposervico < ActiveRecord::Base
  attr_accessible :descricao, :titulo
end

TIR-master/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :role
  # attr_accessible :title, :body
  validates_presence_of :email
  
   ROLES = %w[administrador cliente tecnico]
    
    def role_symbols
        [role.to_sym]
    end
    
    def role?(role)
        role.include?(role.to_s)
    end
  
end

TIR-master/app/controllers/atendimentos_controller.rb
class AtendimentosController < InheritedResources::Base
    load_and_authorize_resource
end

TIR-master/app/controllers/clientes_controller.rb
class ClientesController < InheritedResources::Base
  load_and_authorize_resource
end

TIR-master/app/controllers/empresas_controller.rb
class EmpresasController < InheritedResources::Base
  load_and_authorize_resource
end

TIR-master/app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		flash[:notice] = t(:presentation)
	end

end

TIR-master/app/controllers/registros_controller.rb
class RegistrosController < InheritedResources::Base
  load_and_authorize_resource
end

TIR-master/app/controllers/tecnicos_controller.rb
class TecnicosController < InheritedResources::Base
  load_and_authorize_resource
end

TIR-master/app/helpers/application_helper.rb
module ApplicationHelper

end

TIR-master/app/helpers/atendimentos_helper.rb
module AtendimentosHelper
end

TIR-master/app/helpers/clientes_helper.rb
module ClientesHelper
end

TIR-master/app/helpers/empresas_helper.rb
module EmpresasHelper
end

TIR-master/app/helpers/home_helper.rb
module HomeHelper
end

TIR-master/app/helpers/registros_helper.rb
module RegistrosHelper
end

TIR-master/app/helpers/tecnicos_helper.rb
module TecnicosHelper
end

TIR-master/app/helpers/tipo_servicos_helper.rb
module TipoServicosHelper
end

TIR-master/app/helpers/tiposervicos_helper.rb
module TiposervicosHelper
end

TIR-master/app/views/atendimentos/_form.html.erb
<%= form_for @atendimento, :html => { :multipart => true } do |f| %>

    <p><%= f.label :sumario %><br />
    <%= f.text_field :sumario %></p>

    <p><%= f.label :resolucao %><br />
    <%= f.text_field :resolucao %></p>

    <p><%= f.label :dataAtualizacao %><br />
    <%= f.text_field :dataAtualizacao %></p>
    
    <p><%= f.label :horaAtualizacao %><br />
    <%= f.text_field :horaAtualizacao %></p>

    <p><%= f.label :horaFinalizacao %><br />
    <%= f.text_field :horaFinalizacao %></p>

    <p><%= f.label :status %><br />
    <%= f.text_field :status %></p>

    <p><%= f.label :tecnico %><br />
    <%= f.collection_select :tecnico_id, Tecnico.all, :id, :nome %></br>
    
    <p><%= f.label :descricao %><br />
    <%= f.collection_select :registro_id, Registro.all, :id, :descricao %></br>
    
    <%= f.submit %>

<% end %>

TIR-master/app/views/atendimentos/_form.html.haml
= semantic_form_for [@atendimento] do |form|

  = form.input :sumario, :label => 'Sumario'
  = form.input :resolucao, :label => 'Resolução'
  = form.input :dataAtualizacao, :as => String, :label => 'DataAtualizacao'
  = form.input :horaAtualizacao, :label => 'HoraAtualizacao'
  = form.input :horaFinalizacao, :label => 'HoraFinalizacao'
  = form.input :status, :label => 'Status'
  = form.input :tecnico, :member_label => :nome, :label => 'Técnico'
  = form.input :registro, :member_label => :descricao, :label => 'Registro'
  = form.submit 'Salvar'

TIR-master/app/views/atendimentos/edit.html.erb
<h1>Editing atendimento</h1>

<%= render 'form' %>

<%= link_to 'Show', @atendimento %> |
<%= link_to 'Back', atendimentos_path %>

TIR-master/app/views/atendimentos/index.html.erb
<h1>Lista de atendimentos</h1>

<table>
  <tr>
    <th>Sumario</th>
    <th>Resolução</th>
    <th>Data Atualização</th>
    <th>Hora Atualizacão</th>
    <th>Hora Finalizacão</th>
    <th>Status</th>
    <th>Tecnico</th>
    <th>Registro</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @atendimentos.each do |atendimento| %>
  <tr>
    <td><%= atendimento.sumario %></td>
    <td><%= atendimento.resolucao %></td>
    <td><%= atendimento.dataAtualizacao %></td>
    <td><%= atendimento.horaAtualizacao %></td>
    <td><%= atendimento.horaFinalizacao %></td>
    <td><%= atendimento.status %></td>
    <td><%= atendimento.tecnico.nome %></td>
    <td><%= atendimento.registro.descricao %></td>
    <td><%= link_to 'Exibir', atendimento %></td>
    <td><%= link_to 'Editar', edit_atendimento_path(atendimento) %></td>
    <td><%= link_to 'Excluir', atendimento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Criar Atendimento', new_atendimento_path %>

TIR-master/app/views/atendimentos/new.html.erb
<h1>Novo atendimento</h1>

<%= render 'form' %>

<%= link_to 'Voltar', atendimentos_path %>

TIR-master/app/views/atendimentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Sumario:</b>
  <%= @atendimento.sumario %>
</p>

<p>
  <b>Resolução:</b>
  <%= @atendimento.resolucao %>
</p>

<p>
  <b>DataAtualizacao:</b>
  <%= @atendimento.dataAtualizacao %>
</p>

<p>
  <b>HoraAtualizacao:</b>
  <%= @atendimento.horaAtualizacao %>
</p>

<p>
  <b>HoraFinalizacao:</b>
  <%= @atendimento.horaFinalizacao %>
</p>

<p>
  <b>Status:</b>
  <%= @atendimento.status %>
</p>

<p>
  <b>Tecnico:</b>
  <%= @atendimento.tecnico.nome %>
</p>

<p>
  <b>Registro:</b>
  <%= @atendimento.registro.descricao %>
</p>


<%= link_to 'Editar', edit_atendimento_path(@atendimento) %> |
<%= link_to 'Voltar', atendimentos_path %>